som_deep_informer_big:
  output_mode: default
  redshift_col: &id013 specz
  hdf5_groupname: None
  nproc: 128
  inputs: &id002
  - flux_pgauss_LSST_u
  - flux_pgauss_LSST_g
  - flux_pgauss_LSST_r
  - flux_pgauss_LSST_i
  - flux_pgauss_LSST_z
  - flux_pgauss_LSST_y 
  - flux_pgauss_Y
  - flux_pgauss_J
  - flux_pgauss_H
  input_errs: &id003
  - flux_err_pgauss_LSST_u
  - flux_err_pgauss_LSST_g
  - flux_err_pgauss_LSST_r
  - flux_err_pgauss_LSST_i
  - flux_err_pgauss_LSST_z
  - flux_err_pgauss_LSST_y 
  - flux_err_pgauss_Y
  - flux_err_pgauss_J
  - flux_err_pgauss_H
  zero_points: &id004
  - 22.5
  - 22.5
  - 22.5
  - 22.5
  - 22.5
  - 22.5
  - 22.5
  - 22.5
  - 22.5  
  som_shape: &id005 [64, 64]
  som_minerror: 0.01
  som_wrap: &id016 false
  som_take_log: &id015 True
  convert_to_flux: &id014 false
  set_threshold: true
  thresh_val: 1.0e-05
  thresh_val_err: 1.0e-05
  name: som_deep_informer_big
  model: out_specz_cosmos20_classic_full/model_deep.pkl
  som_takelog: false
  config: None
som_wide_informer_big:
  output_mode: default
  redshift_col: *id013
  hdf5_groupname: None
  nproc: 128
  inputs: &id006
  - flux_pgauss_LSST_u
  - flux_pgauss_LSST_g
  - flux_pgauss_LSST_r
  - flux_pgauss_LSST_i
  - flux_pgauss_LSST_z
  - flux_pgauss_LSST_y 
  - flux_pgauss_Y
  - flux_pgauss_J
  - flux_pgauss_H
  input_errs: &id007
  - flux_err_pgauss_LSST_u
  - flux_err_pgauss_LSST_g
  - flux_err_pgauss_LSST_r
  - flux_err_pgauss_LSST_i
  - flux_err_pgauss_LSST_z
  - flux_err_pgauss_LSST_y 
  - flux_err_pgauss_Y
  - flux_err_pgauss_J
  - flux_err_pgauss_H
  zero_points: &id008
  - 22.5
  - 22.5
  - 22.5
  - 22.5
  - 22.5
  - 22.5
  - 22.5
  - 22.5
  - 22.5  

  som_shape: &id009 [32, 32]
  som_minerror: 0.005
  som_wrap: *id016
  som_take_log: *id015
  convert_to_flux: *id014
  set_threshold: true
  thresh_val: 1.0e-05
  thresh_val_err: 1.0e-05
  name: som_wide_informer_big
  model: out_specz_cosmos20_classic_full/model_wide.pkl
  som_takelog: false
  config: None

checkinputdeep:
  output_mode: default
  checked: out_specz_cosmos20_classic_full/checked_deep.txt 
  config: None
  nproc: 1
  name: checkinputdeep
  inputs: *id002
  input_errs: *id003
checkinputspec:
  output_mode: default
  checked: out_specz_cosmos20_classic_full/checked_spec.txt 
  config: None
  nproc: 1
  name: checkinputspec
  inputs: *id002
  input_errs: *id003

checkinputwide:
  output_mode: default
  checked: out_specz_cosmos20_classic_full/checked_wide.txt 
  config: None
  nproc: 1
  name: checkinputwide
  inputs: *id006
  input_errs: *id007




som_deepdeep_estimator:
  output_mode: default
  chunk_size: 20000
  hdf5_groupname: None
  zmin: 0.0
  zmax: &id011 3.05
  nzbins: &id012 62
  calculated_point_estimates: &id001 []
  recompute_point_estimates: false
  redshift_col: *id013
  inputs: *id002
  input_errs: *id003
  zero_points: *id004
  som_shape: *id005
  som_minerror: 0.01
  som_wrap: *id016
  som_take_log: *id015
  convert_to_flux: *id014
  set_threshold: true
  thresh_val: 1.0e-05
  debug: false
  name: som_deepdeep_estimator
  model: out_specz_cosmos20_classic_full/model_deep.pkl
  assignment: out_specz_cosmos20_classic_full/deepdata_deep_assignment.hdf5
  thresh_val_err: 1.0e-05
  config: None
som_deepwide_estimator:
  output_mode: default
  chunk_size: 20000
  hdf5_groupname: None
  zmin: 0.0
  zmax: *id011
  nzbins: *id012
  calculated_point_estimates: *id001
  recompute_point_estimates: false
  redshift_col: *id013
  inputs: *id006
  input_errs: *id007
  zero_points: *id008
  som_shape: *id009
  som_minerror: 0.005
  som_wrap: *id016
  som_take_log: *id015
  convert_to_flux: *id014
  set_threshold: true
  thresh_val: 1.0e-05
  debug: false
  name: som_deepwide_estimator
  model: out_specz_cosmos20_classic_full/model_wide.pkl
  assignment: out_specz_cosmos20_classic_full/deepdata_wide_assignment.hdf5
  thresh_val_err: 1.0e-05
  config: None
som_deepspec_estimator:
  output_mode: default
  chunk_size: 2000
  hdf5_groupname: None
  zmin: 0.0
  zmax: *id011
  nzbins: *id012
  calculated_point_estimates: *id001
  recompute_point_estimates: false
  redshift_col: *id013
  inputs: *id002
  input_errs: *id003
  zero_points: *id004
  som_shape: *id005
  som_minerror: 0.01
  som_wrap: *id016
  som_take_log: *id015
  convert_to_flux: *id014
  set_threshold: true
  thresh_val: 1.0e-05
  debug: false
  name: som_deepspec_estimator
  model: out_specz_cosmos20_classic_full/model_deep.pkl
  thresh_val_err: 1.0e-05
  config: None
  assignment: out_specz_cosmos20_classic_full/deepspecdata_deep_assignment.hdf5
som_widewide_estimator:
  output_mode: default
  chunk_size: 20000
  hdf5_groupname: None
  zmin: *id011
  zmax: *id012
  nzbins: 301
  calculated_point_estimates: *id001
  recompute_point_estimates: false
  redshift_col: *id013
  inputs: *id006
  input_errs: *id007
  zero_points: *id008
  som_shape: *id009
  som_minerror: 0.005
  som_wrap: *id016
  som_take_log: *id015
  convert_to_flux: *id014
  set_threshold: true
  thresh_val: 1.0e-05
  debug: false
  name: som_widewide_estimator
  model: out_specz_cosmos20_classic_full/model_wide.pkl
  assignment: out_specz_cosmos20_classic_full/widedata_wide_assignment.hdf5
  thresh_val_err: 1.0e-05
  config: None
som_widespec_estimator:
  output_mode: default
  chunk_size: 2000
  hdf5_groupname: None
  zmin: 0.0
  zmax: *id011
  nzbins: *id012
  calculated_point_estimates: *id001
  recompute_point_estimates: false
  redshift_col: *id013
  inputs: *id006
  input_errs: *id007
  zero_points: *id008
  som_shape: *id009
  som_minerror: 0.005
  som_wrap: *id016
  som_take_log: *id015
  convert_to_flux: *id014
  set_threshold: true
  thresh_val: 1.0e-05
  debug: false
  name: som_widespec_estimator
  model: out_specz_cosmos20_classic_full/model_wide.pkl
  assignment: out_specz_cosmos20_classic_full/specdata_wide_assignment.hdf5
  thresh_val_err: 1.0e-05
  config: None
som_pzc_stage:
  output_mode: default
  chunk_size: 2000
  hdf5_groupname: None
  zbins_min: 0.0
  zbins_max: *id011
  zbins_dz: &id020 0.05
  calculated_point_estimates: *id001
  recompute_point_estimates: false
  inputs: &id010
  redshift_col: *id013
  deep_groupname: None
  bin_edges: &id023
  - 0.0
  - 0.65
  - 1.0
  - 1.3
  - 2.0
  - 3.0
  zbins_min: 0.0
  zbins_max: *id011
  zbins_dz: *id020
  name: som_pzc_stage
  pz_c: out_specz_cosmos20_classic_full/pz_c.hdf5
  config: None
pcchat_stage:
  output_mode: default
  chunk_size: 2000
  hdf5_groupname: None
  zmin: 0.0
  zmax: *id011
  nzbins: *id012
  calculated_point_estimates: *id001
  recompute_point_estimates: false
  inputs: *id010
  name: pcchat_stage
  deep_som_size: 4096
  wide_som_size: 1024
  redshift_col: *id013
  config: None
  pc_chat: ./out_specz_cosmos20_classic_full/pc_chat_pcchat_stage.hdf5
sompz_pzchat:
  output_mode: default
  chunk_size: 2000
  hdf5_groupname: None
  zmin: 0.0
  zmax: *id011
  nzbins: *id012
  calculated_point_estimates: *id001
  recompute_point_estimates: false
  inputs: *id010
  redshift_col: *id013
  bin_edges: *id023
  zbins_min: 0.0
  zbins_max: *id011
  zbins_dz: *id020
  name: sompz_pzchat
  config: None
  pz_chat: out_specz_cosmos20_classic_full/pz_chat.hdf5
sompz_pchat:
  output_mode: default
  som_shape: *id009
  chunk_size: 2000
  hdf5_groupname: None
  inputs: *id010
  name: sompz_pchat
  config: None
  pchat: out_specz_cosmos20_classic_full/pchat.hdf5
sompz_tomobin:
  output_mode: default
  chunk_size: 2000
  hdf5_groupname: None
  zmin: 0.0
  zmax: *id011
  nzbins: *id012
  calculated_point_estimates: *id001
  recompute_point_estimates: false
  inputs: *id010
  redshift_col: *id013
  bin_edges: *id023
  zbins_min: 0.0
  zbins_max: *id011
  zbins_dz: *id020
  name: sompz_tomobin
  wide_som_size: 1024
  deep_som_size: 4096
  tomo_bins_wide: ./out_specz_cosmos20_classic_full/tomo_bins_wide.hdf5
  config: None
sompz_nz:
  output_mode: default
  chunk_size: 2000
  hdf5_groupname: None
  zmin: 0.0
  zmax: *id011
  nzbins: *id012
  calculated_point_estimates: *id001
  recompute_point_estimates: false
  inputs: *id010
  redshift_col: *id013
  bin_edges: *id023
  zbins_min: 0.0
  zbins_max: *id011
  zbins_dz: *id020
  name: sompz_nz
  wide_som_size: 625
  deep_som_size: 1024
  nz: ./out_specz_cosmos20_classic_full/FINAL_NZ.hdf5
  config: None
PreparePZRealizationsPipe:
  output_mode: default
  redshift_sample_uncertainty: &id024 False
  photometric_zeropoint_deep: &id017 True 
  photometric_zeropoint_wide: &id018 True
  photometric_skybackground_deep: &id019 True
  photometric_skybackground_wide: &id022 True
  deepfield_zeropoint_data: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001] 
  widefield_zeropoint_data: [0.0002, 0.0002, 0.0002, 0.0002, 0.0002, 0.0002, 0.0002, 0.0002, 0.0002] 
  num_lhc_points: &id021 5
  LHC_samples_deep_zp: ./out_specz_cosmos20_classic_full/LHC_samples_deep_zp.fit
  LHC_samples_wide_zp: ./out_specz_cosmos20_classic_full/LHC_samples_wide_zp.fit
  LHC_samples_sky: ./out_specz_cosmos20_classic_full/LHC_samples_sky.fit
PhotozDeepDeepZpDustPipe:
  output_mode: default
  chunk_size: 2000
  hdf5_groupname: None
  zmin: 0.0
  zmax: *id011
  nzbins: *id012
  calculated_point_estimates: *id001
  recompute_point_estimates: false
  redshift_col: *id013
  inputs: *id002
  input_ra_col: ra
  input_dec_col: dec
  input_errs: *id003
  zero_points: *id004
  som_shape: *id005
  som_minerror: 0.005
  som_wrap: *id016
  som_take_log: *id015
  convert_to_flux: *id014
  set_threshold: true
  thresh_val: 1.0e-05
  debug: false
  photometric_zeropoint: *id017
  photometric_skybackground: *id019
  name: PhotozDeepDeepZpDustPipe
  deep_model: out_specz_cosmos20_classic_full/model_deep.pkl
  assignment: out_specz_cosmos20_classic_full/deepdata_deep_zeropoint_assignment.hdf5
  thresh_val_err: 1.0e-05
  config: None

PhotozDeepWideZpDustPipe:
  output_mode: default
  chunk_size: 2000
  hdf5_groupname: None
  zmin: 0.0
  zmax: *id011
  nzbins: *id012
  calculated_point_estimates: *id001
  recompute_point_estimates: false
  redshift_col: *id013
  inputs: *id006
  input_ra_col: ra
  input_dec_col: dec
  input_errs: *id007
  zero_points: *id008
  som_shape: *id009
  som_minerror: 0.005
  som_wrap: *id016
  som_take_log: *id015
  convert_to_flux: *id014
  set_threshold: true
  thresh_val: 1.0e-05
  debug: false
  photometric_zeropoint: *id018
  photometric_skybackground: *id022
  name: PhotozDeepWideZpDustPipe
  deep_model: out_specz_cosmos20_classic_full/model_wide.pkl
  assignment: out_specz_cosmos20_classic_full/deepdata_wide_zeropoint_assignment.hdf5
  thresh_val_err: 1.0e-05
  config: None

PhotozWideWideZpDustPipe:
  output_mode: default
  chunk_size: 2000
  hdf5_groupname: None
  zmin: 0.0
  zmax: *id011
  nzbins: *id012
  calculated_point_estimates: *id001
  recompute_point_estimates: false
  redshift_col: *id013
  inputs: *id006
  input_ra_col: ra
  input_dec_col: dec
  input_errs: *id007
  zero_points: *id008
  som_shape: *id009
  som_minerror: 0.005
  som_wrap: *id016
  som_take_log: *id015
  convert_to_flux: *id014
  set_threshold: true
  thresh_val: 1.0e-05
  debug: false
  photometric_zeropoint: *id018
  photometric_skybackground: *id022
  name: PhotozWideWideZpDustPipe
  deep_model: out_specz_cosmos20_classic_full/model_wide.pkl
  assignment: out_specz_cosmos20_classic_full/widedata_wide_zeropoint_assignment.hdf5
  thresh_val_err: 1.0e-05
  config: None
  
Samplevariance: 
    area:  20.0
    zbins_zmin: 0.0
    zbins_zmax: *id011
    zbins_dz: *id020 
    Sample_variance: ./out_specz_cosmos20_classic_full/Sample_variance.fit
    
RunPZRealizationsPipe:
    redshift_col: *id013
    shot_noise: True
    sample_variance: False
    redshift_sample_uncertainty: *id024 
    photometric_zeropoint_deep: *id017
    photometric_zeropoint_wide: *id018
    photometric_skybackground_deep: *id019
    photometric_skybackground_wide: *id022 
    num_lhc_points: *id021 
    num_3sdir: 100
    bands: *id006 
    inputs: *id006
    input_errs: *id007
    som_shape: *id005
    photoz_realizations: ./out_specz_cosmos20_classic_full/photoz_realizations.hdf5
    name: RunPZRealizationsPipe
    zbins_min: 0.0
    zbins_max: *id011
    zbins_dz: *id020
