output_dir: ./
log_dir: out_true
resume: True # If all the outputs for a stage already exist then do not re-run that stage
config: ../yaml/config_ou_tae_02062026_true.yaml
modules: rail
inputs:
  input_deep_data: ./out/phot_OU2024-IMCOM_300sq-arcmin_ugrizyYJH_clipzero.parquet
  input_spec_data: ./out/phot_OU2024-IMCOM_300sq-arcmin_ugrizyYJH_clipzero.parquet
  input_wide_data: ./out/phot_OU2024-IMCOM_300sq-arcmin_ugrizyYJH_clipzero.parquet
stages:
- name: som_deep_informer_big
  classname: SOMPZInformer
  nprocess: 1
  module_name: rail.estimation.algos.sompz
  aliases:
    model: model_som_deep_informer
    input_data: input_deep_data
site:
  max_threads: 128
  name: local

